import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Results from "../components/results/Results";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Movie V1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Results />
    </div>
  );
}
