import Head from "next/head";
import request from "../utils/request";
import Navbar from "../components/Navbar";
import Results from "../components/results/Results";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Movie V1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <Results results={data.results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const { type } = context.query;

  const url = type
    ? `https://api.themoviedb.org/3${request[type].url}`
    : `https://api.themoviedb.org/3${request["fetchTrending"].url}`;

  const req = await fetch(url);

  const data = await req.json();

  return {
    props: {
      data,
    },
  };
}
